import * as React from "react";
import {
    AnswersHeadlessProvider,
    SandboxEndpoints,
  } from "@yext/answers-headless-react";
  import {
    StandardCard,
    StandardSection,
    UniversalResults,
    SearchBar,
    VerticalResults
  } from "@yext/answers-react-components";

// Search Cards
import DoctorTile from "../components/search/cards/DoctorTile";
import GenericCard from "../components/search/cards/GenericCard";

// Search Sections
import GridSection from "../components/search/sections/GridSection";

// Pages components
import Header from "../components/header";
import Footer from "../components/footer";
import PageLayout from "../components/PageLayout";
import SearchLayout from "../components/search/SearchLayout";

import "../index.css";
import {
  Template,
  GetPath,
  TransformProps,
  GetRedirects,
  TemplateConfig,
  TemplateProps,
  TemplateRenderProps,
  GetHeadConfig,
  HeadConfig,
} from "@yext/pages";

export const config: TemplateConfig = {
    name: "search",
  };

export const getPath: GetPath<TemplateProps> = () => {
 return `search`;
};

export const getHeadConfig: GetHeadConfig<TemplateRenderProps> = ({relativePrefixToRoot, path, document}): HeadConfig => {
  return {
    title: "Search Page",
    charset: "UTF-8",
    viewport: "width=device-width, initial-scale=1",
    tags: [
      {
        type: "meta",
        attributes: {
          description: "This site was generated by the Yext SSG",
        },
      },
    ],
  };
};

const defaultVerticalConfig = {
  CardComponent: GenericCard,
  SectionComponent: GridSection,
};

const Search: Template<TemplateRenderProps> = ({relativePrefixToRoot, path, document}) => {
    const {
      _site, 
    } = document;

  return (
    <>
      <body className="font-main">
        <Header site={_site}></Header>
        <div className="centered-container">
          <PageLayout >
            <div className="text-4xl font-semibold pt-10">Search Results</div>
            <div className="section">
              <SearchBar />
            </div>
            <UniversalResults 
              verticalConfigMap={{
                healthcare_professionals: {
                  ...defaultVerticalConfig,
                  label: "Dentists",
                  CardComponent: DoctorTile
                },
                services: {
                  ...defaultVerticalConfig,
                  label: "Services",
                  CardComponent: GenericCard
                },
                subServices: {
                  ...defaultVerticalConfig,
                  label: "Sub-Services & Articles",
                  CardComponent: GenericCard
                },
              }}
            />
            </PageLayout>
        </div>
        <Footer site={_site}></Footer>
      </body>
    </>
  );
};

export default Search;
